# Generated by Django 4.2.7 on 2025-02-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
    ]
