# Generated by Django 4.2.7 on 2025-03-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_visit_agent_remove_visit_pharmacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='thread_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
